import { adminClient, json } from "../_shared/auth.ts";

const corsHeaders = { "access-control-allow-origin": "*", "access-control-allow-headers": "authorization, x-client-info, apikey, content-type", "access-control-allow-methods": "POST, OPTIONS" };
function publicJson(body: unknown, status = 200) { const response = json(body, status); corsHeaders && Object.entries(corsHeaders).forEach(([key, value]) => response.headers.set(key, value)); return response; }
function errorMessage(error: unknown) {
  return error instanceof Error ? error.message : typeof error === "object" && error && "message" in error ? String((error as { message?: unknown }).message) : "request failed";
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return publicJson({ ok: true });
  if (req.method !== "POST") return publicJson({ error: "method not allowed" }, 405);
  try {
    const body = await req.json();
    const token = String(body.token || "");
    if (token.length < 32) return publicJson({ error: "invalid share token" }, 401);
    const admin = adminClient();
    const hash = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(token));
    const tokenHash = [...new Uint8Array(hash)].map(byte => byte.toString(16).padStart(2, "0")).join("");
    const { data: link, error: linkError } = await admin.from("share_links").select("id,scope,provider_id,is_active,expires_at").or(`public_token.eq.${token},token_hash.eq.${tokenHash}`).maybeSingle();
    if (linkError || !link || !link.is_active || (link.expires_at && new Date(link.expires_at) <= new Date())) return publicJson({ error: "share link is invalid or revoked" }, 401);
    await admin.from("share_links").update({ last_accessed_at: new Date().toISOString() }).eq("id", link.id);
    let query = admin.from("providers").select("id,user_code,name,telegram_username,upi_id,mobile,apk_mobile,gpay_login_id,funding_model,commission_limit_inr,unique_deposit_address,is_active,status,pause_reason").in("status", ["active", "paused"]);
    if (link.scope === "user") query = query.eq("id", link.provider_id);
    const { data: providers, error } = await query;
    if (error) throw error;
    if (link.scope === "user" && (!providers || providers.length !== 1)) return publicJson({ error: "user share link is unavailable" }, 404);
    const ids = (providers || []).map(provider => provider.id);
    const [ledger, deposits, qrs, merchantSettlements, withdrawals, upiAccounts, charges] = await Promise.all([
      ids.length ? admin.from("ledger_entries").select("id,provider_id,upi_account_id,entry_type,amount_inr,amount_usdt,rate,merchant_commission_rate,merchant_commission_inr,bank_name,account_number,transaction_date,note,status,is_voided,voided_at,void_reason,edited_at,edit_reason").in("provider_id", ids).order("transaction_date", { ascending: false }).limit(link.scope === "user" ? 250 : 500) : Promise.resolve({ data: [], error: null }),
      ids.length ? admin.from("deposit_requests").select("id,provider_id,requested_usdt,expected_usdt,rate,inr_value,destination_address,status,tx_hash,created_at,confirmed_at,source").in("provider_id", ids).order("created_at", { ascending: false }).limit(link.scope === "user" ? 250 : 500) : Promise.resolve({ data: [], error: null }),
      ids.length ? admin.from("provider_qr_codes").select("id,provider_id,upi_account_id,storage_path,display_name").in("provider_id", ids) : Promise.resolve({ data: [], error: null }),
      link.scope === "merchant" ? admin.from("merchant_settlements").select("id,amount_usdt,rate,amount_inr,commission_inr,proof_tx_hash,proof_url,proof_note,created_at").order("created_at", { ascending: false }).limit(500) : Promise.resolve({ data: [], error: null }),
      link.scope === "merchant" ? admin.from("withdrawal_requests").select("id,requester_type,provider_id,upi_account_id,amount_usdt,rate,amount_inr,destination_address,status,proof_tx_hash,proof_url,proof_note,created_at,paid_at,is_voided,voided_at,void_reason,edited_at,edit_reason").eq("requester_type", "merchant").in("status", ["pending", "paid"]).order("created_at", { ascending: false }).limit(500) : link.scope === "user" ? admin.from("withdrawal_requests").select("id,requester_type,provider_id,upi_account_id,amount_usdt,rate,amount_inr,destination_address,status,proof_tx_hash,proof_url,proof_note,created_at,paid_at,is_voided,voided_at,void_reason,edited_at,edit_reason").eq("requester_type", "provider").eq("provider_id", link.provider_id).in("status", ["pending", "paid"]).order("created_at", { ascending: false }).limit(250) : Promise.resolve({ data: [], error: null }),
      ids.length ? admin.from("provider_upi_accounts").select("id,provider_id,label,upi_id,mobile,apk_mobile,gpay_login_id,qr_data,status,merchant_operational,blocked_by_user,blocked_by_admin,admin_block_reason,archived_at,configured_limit_inr,allocated_limit_inr,bank_name,bank_account_number,account_holder_name,ifsc_code,bank_branch,account_note").in("provider_id", ids) : Promise.resolve({ data: [], error: null }),
      link.scope === "merchant" ? admin.from("merchant_charges").select("id,provider_id,upi_account_id,amount_inr,user_name,upi_id,mobile,charge_date,reference,note,status,created_at").eq("status", "active").order("charge_date", { ascending: false }).limit(500) : Promise.resolve({ data: [], error: null }),
    ]);
    if (ledger.error || deposits.error || qrs.error || merchantSettlements.error || withdrawals.error || upiAccounts.error || charges.error) throw ledger.error || deposits.error || qrs.error || merchantSettlements.error || withdrawals.error || upiAccounts.error || charges.error;
    const privateView = link.scope === "user";
    const { data: appSettings } = privateView || link.scope === "merchant" ? await admin.from("app_settings").select("settlement_rate,deposit_base_rate,deposit_markup_pct,commission_rate_pct,admin_trc20_address").eq("id", true).maybeSingle() : { data: null };
    const providerAccounting = new Map((await Promise.all((providers || []).map(async provider => {
      const { data } = await admin.rpc("accounting_for_provider", { p_provider_id: provider.id });
      return [provider.id, data?.[0] || {}] as const;
    }))));
    const upiAccountingRows = new Map((await Promise.all((upiAccounts.data || []).map(async account => {
      const { data } = await admin.rpc("accounting_for_upi", { p_upi_account_id: account.id });
      return [account.id, data?.[0] || null] as const;
    }))));
    const signedQrRows = new Map((await Promise.all((qrs.data || []).map(async qr => {
      const { data } = await admin.storage.from("provider-qr").createSignedUrl(qr.storage_path, 300);
      return [qr.id, data?.signedUrl || ""] as const;
    }))));
    const merchantSummary = { totalCollectionInr: 0, frozenInr: 0, availableInr: 0, availableUsdt: 0, settledInr: 0, settledUsdt: 0, settlementRate: 107, commissionEarnedInr: 0 };
    merchantSummary.settlementRate = Number(appSettings?.settlement_rate || 107);
    const state = { settings: privateView ? { settlementRate: Number(appSettings?.settlement_rate || 107), depositBaseRate: Number(appSettings?.deposit_base_rate || 107), depositMarkupPct: Number(appSettings?.deposit_markup_pct ?? 3), commissionRate: Number(appSettings?.commission_rate_pct || 3.5), adminTrc20Address: appSettings?.admin_trc20_address || "", usdtContract: "" } : { settlementRate: merchantSummary.settlementRate, depositBaseRate: 0, depositMarkupPct: 0, commissionRate: 0, adminTrc20Address: "", usdtContract: "" }, users: [], entries: [], deposits: [], withdrawals: privateView ? [] : [], audit: [], merchantSettlement: link.scope === "merchant" ? merchantSummary : null } as any;
    for (const provider of providers || []) {
      const accounting = providerAccounting.get(provider.id) || {};
      const providerWithdrawals = (withdrawals.data || []).filter(row => row.provider_id === provider.id), paidCommission = providerWithdrawals.filter(row => row.status === "paid").reduce((sum, row) => sum + Number(row.amount_inr || 0), 0), reservedCommission = providerWithdrawals.filter(row => row.status === "pending").reduce((sum, row) => sum + Number(row.amount_inr || 0), 0), earnedCommission = Number(accounting.successful_withdrawal_inr || 0) * Number(appSettings?.commission_rate_pct || 3.5) / 100;
      const resolvedDepositAddress = provider.unique_deposit_address || appSettings?.admin_trc20_address || "";
      const user = { id: provider.user_code, remoteId: provider.id, name: provider.name, telegram: provider.telegram_username || "", upi: provider.upi_id || "", mobile: provider.mobile || "", apk: provider.apk_mobile || "", gpayLogin: provider.gpay_login_id || "", qrs: [], token: privateView ? token : "", active: provider.status !== "deleted", status: provider.status, pauseReason: provider.pause_reason || "", upiAccounts: (upiAccounts.data || []).filter(account => account.provider_id === provider.id).map(account => ({ id: account.id, label: account.label, upi: account.upi_id || "", mobile: account.mobile || "", apk: account.apk_mobile || "", gpayLogin: account.gpay_login_id || "", qrData: account.qr_data || "", status: account.status, merchantOperational: account.merchant_operational, blockedByUser: account.blocked_by_user === true, blockedByAdmin: account.blocked_by_admin === true, adminBlockReason: account.admin_block_reason || "", archivedAt: account.archived_at || "", configuredLimit: Number(account.configured_limit_inr || 0), allocatedLimit: Number(account.allocated_limit_inr || 0), bankName: account.bank_name || "", bankAccountNumber: account.bank_account_number || "", accountHolderName: account.account_holder_name || "", ifscCode: account.ifsc_code || "", bankBranch: account.bank_branch || "", accountNote: account.account_note || "" })), accounting: { collection_inr: accounting.collection_inr || 0, collection_capacity_inr: accounting.collection_capacity_inr || 0, frozen_inr: accounting.frozen_inr || 0, successful_withdrawal_inr: accounting.successful_withdrawal_inr || 0, user_usdt_inr: accounting.user_usdt_inr || 0, merchant_settled_inr: accounting.merchant_settled_inr || 0, confirmed_deposit_inr: privateView ? accounting.confirmed_deposit_inr || 0 : 0, commission_earned_inr: privateView ? earnedCommission : 0, commission_paid_inr: privateView ? paidCommission : 0, commission_reserved_inr: privateView ? reservedCommission : 0, commission_available_inr: privateView ? Math.max(0, earnedCommission - paidCommission - reservedCommission) : 0 } };
      for (const account of user.upiAccounts) { const value = upiAccountingRows.get(account.id); if (value) { account.accounting = value; account.collection = Number(value.total_collection_inr || 0); account.availableLimit = Number(value.available_limit_inr || 0); } account.qrs = []; for (const qr of (qrs.data || []).filter(row => row.upi_account_id === account.id)) { account.qrs.push({ id: qr.id, name: qr.display_name || "QR", storagePath: qr.storage_path, data: signedQrRows.get(qr.id) || "" }); } }
      if (privateView) { user.fundingMode = provider.funding_model; user.depositAddress = provider.unique_deposit_address || ""; user.uniqueDepositAddress = provider.unique_deposit_address || ""; user.companyDepositAddress = appSettings?.admin_trc20_address || ""; user.resolvedDepositAddress = resolvedDepositAddress; }
      for (const qr of (qrs.data || []).filter(row => row.provider_id === provider.id && !row.upi_account_id)) {
        user.qrs.push({ id: qr.id, name: qr.display_name || "QR", storagePath: qr.storage_path, data: signedQrRows.get(qr.id) || "" });
      }
      state.users.push(user);
    }
    for (const row of ledger.data || []) { if (privateView || row.entry_type === "collection") state.entries.push({ id: row.id, userId: (providers || []).find(provider => provider.id === row.provider_id)?.user_code, accountId: row.upi_account_id || "", type: row.entry_type, amount: row.amount_inr, usdt: row.amount_usdt, rate: row.rate, bank: row.bank_name, account: row.account_number, date: row.transaction_date, note: row.note, status: row.status, isVoided: row.is_voided === true, voidedAt: row.voided_at || "", voidReason: row.void_reason || "", editedAt: row.edited_at || "", editReason: row.edit_reason || "" }); if (link.scope === "merchant" && row.status !== "void" && row.is_voided !== true) { const amount = Number(row.amount_inr || 0), usdt = Number(row.amount_usdt || 0), rate = Number(row.rate || 107); if (row.entry_type === "collection" && row.status === "posted") merchantSummary.totalCollectionInr += amount; if (row.entry_type === "frozen" && row.status === "active") merchantSummary.frozenInr += amount; if (row.entry_type === "merchant_usdt" && row.status === "posted") { merchantSummary.settledUsdt += usdt; merchantSummary.settledInr += Number(row.amount_inr || usdt * rate); merchantSummary.commissionEarnedInr += Number(row.merchant_commission_inr || (usdt * rate * Number(row.merchant_commission_rate || 4.5) / 100)); } } }
    if (link.scope === "merchant") { for (const row of merchantSettlements.data || []) { merchantSummary.settledUsdt += Number(row.amount_usdt || 0); merchantSummary.settledInr += Number(row.amount_inr || 0); merchantSummary.commissionEarnedInr += Number(row.commission_inr || 0); } const reserved = (withdrawals.data || []).reduce((sum, row) => sum + Number(row.amount_inr || 0), 0), chargesInr = (charges.data || []).reduce((sum, row) => sum + Number(row.amount_inr || 0), 0); merchantSummary.chargesInr = chargesInr; merchantSummary.availableInr = Math.max(0, merchantSummary.totalCollectionInr - merchantSummary.frozenInr - merchantSummary.settledInr - reserved - chargesInr); merchantSummary.availableUsdt = merchantSummary.availableInr / merchantSummary.settlementRate; }
    if (privateView) { for (const row of deposits.data || []) state.deposits.push({ id: row.id, userId: (providers || []).find(provider => provider.id === row.provider_id)?.user_code, requestedUsdt: row.requested_usdt, expectedUsdt: row.expected_usdt, rate: row.rate, inrValue: row.inr_value, address: row.destination_address, status: row.status, txHash: row.tx_hash, createdAt: row.created_at, confirmedAt: row.confirmed_at, source: row.source }); for (const row of withdrawals.data || []) state.withdrawals.push({ id: row.id, requesterType: row.requester_type, userId: state.users[0]?.id, accountId: row.upi_account_id || "", amountUsdt: row.amount_usdt, rate: row.rate, amountInr: row.amount_inr, address: row.destination_address, status: row.status, createdAt: row.created_at, paidAt: row.paid_at, isVoided: row.is_voided === true, voidedAt: row.voided_at || "", voidReason: row.void_reason || "", editedAt: row.edited_at || "", editReason: row.edit_reason || "" }); }
    return publicJson({ scope: link.scope, state });
  } catch (error) { return publicJson({ error: errorMessage(error) }, 400); }
});
